---
# tasks file for setting up mastodon instance on ubuntu20.04
- include: ssh_port_fallback.yml
- include: harden.yml
#  become: true
#  apply tags,become
#  when: harden_os
#  tags: harden

- include: docker.yml
#  become: true
#  apply tags,become
#  when: harden_os
#  tags: harden

- include: mastodon.yml
#  become: true
#  apply tags,become
#  when: harden_os
#  tags: harden
