---
- name: "NOTSCORED | 3.5.1.6 | PATCH | Ensure firewall rules exist for all open ports"
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  loop:
    - '4000'
    - '3000'
    - '80'
    - '443'
    - '22'
- name: Creates directory structure for mastodon itself
  file:
    path: /home/{{ main_user }}/mastodon/public/system
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0775

- name: Creates directory structure for mastodon db data
  file:
    path: /home/{{ main_user }}/mastodon/postgres14
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0775

- name: Creates directory structure for nginx data
  file:
    path: /home/{{ main_user }}/mastodon/redis
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0775

- name: copy docker compose to server
  become_user: "{{ main_user }}"
  copy:
    src: files/docker-compose.yml
    dest: /home/{{ main_user }}/mastodon/

- name: bring down mastodon docker-compose
  become_user: "{{ main_user }}"
  docker_compose:
    project_src: /home/{{ main_user }}/mastodon/
    state: absent
  register: __remove_mastodon
  tags:
    - bring-down

- name: update permissions
  file:
    path: /home/{{ main_user }}
    state: directory
    recurse: yes
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0775

- name: setup nginx reverse proxy from template
  template:
    src: templates/nginx.conf.j2
    dest: /home/{{ main_user }}/mastodon/nginx/nginx.conf

- name: docker compose up
  become_user: "{{ main_user }}"
  docker_compose:
    project_src: /home/{{ main_user }}/mastodon/
    state: present
  register: __mastodon

- name: debug docker compose down
  debug:
    var: __remove_mastodon

- name: debug docker compose up debug
  debug:
    var: __mastodon
